= transliteration-learner-from-graphs

A technology to design transliteration systems from scratch in an inclusive way for language experts.

=== Motivation & Approach


==== Motivation

Transliteration is the process of transforming a language into another
script, transforming the letters such as to maintain the  sounds.

Languages are obviously subject to very complex rules making the above process
 quite complicated.
It is especially the case if no corpora are available to train
neural networks or other techniques on.

No corpora are available with Farsi at the time of the creation of this
library, and so we needed to build the transliteration strategy from scratch.

Building a proper library needs the composition
of mappings of  language roots, lemmas and affixes
 into constructions via complex rules.
The software is binding a set of mappings
via and extensive number of rules.

In the design of the rules and on top of the mappings,
many components are involved:
Part of Speech tagger, lemmatizer and stemming.

In addition to this all, the work on a computerised solution
 requires also a successful interplay  between
 a software developer and a linguist/language specialist.

Ideally, such a collaboration should be made easier,
 allowing for visualisation, scaling and an intuitive solution.


==== Approach

For achieving this, we propose the following approach:

1. Graphical Editor

  * allowing a linguist to easily design and reshape complex rules

2. Learning Code

  * software capable to convert above mentionned graphical rules into code.

3. Transliteration of massive Farsi dataset

  * We have put together massive dataset for this purpose.

4. Training of neural network architecture

  * transliteration is approached as translation and with similar tools.


=== Library + Workflow

The Library is structured as described below.
More details are provided within the subfolders.

The workflow is also sketched.

1. https://github.com/interscript/transliteration-learner-from-graphs/tree/main/learn-graph[learn-graph]

  * code: creates customised transliteration code from expert diagrams and mappings
    code currently support lucidcharts, whereas basic format has to be followed
    for diagrams design
  * tests and benchmarks: basics benchmarks can run from a simple data format,
      allowing for easy evaluation of new diagrams or tweaks in the code.
  * data + transliteration for learning: We provide with farsi datasets that can be
    transliterated by our code.

2. https://github.com/interscript/transliteration-learner-from-graphs/tree/main/python-nnets-torch[python-nnets-torch]

  * training of transformer architecture, transliteration learned as transliteration
  * export and decomposition of best models into onnx format, so that they can be used in production

3. https://github.com/interscript/transliteration-learner-from-graphs/tree/main/lib[lib]

  * production code in ruby
  * importing and combining transformer models trained in python to transliterate
    samples or files
