== Strict ISO Farsi Example

==== Intro

Farsi learn is a software allowing a non technical experts to sketch
rules and logic steps needed for the task of transliteration of Farsi.

We have created this system to speed up and make flexible this general
part of the work.

While the language specialist can design and try easily his own rules,
the developer implements the code corresponding to the rules. This way
both tasks and roles are well defined and confined.

== Components & Steps

==== Learning Strategy

We refer to QUICKSTART and the article in docs in the main branch for explanations.
 

==== Diagram format

We structure logic flows as a set of graphs.
This scales by allowing a graph to call other graph logics.

Any diagram respecting the same formatting can be straightforwardly transformed
into code:

  * Entry Point of logic flows (or subfows):
   Start of any logic of sub logic Curly Brace Note
  * Nodes: Decision, Process and Terminator.

Obviously, the nodes and entries have to be connected by arrows in a consistent
manner.


==== Mappings

Here, *learn-graph/resources/Strict+ShortVowelsOnlyIf.txt*



==== Install Julia

https://julialang.org/downloads/[julia downloads]

==== Connect to Correct Python Path/Dependencies
[source,bash]
----
ENV[``PYTHON''] = ``…my python path with hazm installed…''
import Pkg; Pkg.add(``PyCall''); Pkg.build(``PyCall'')
----

==== Julia Dependencies

[source,bash]
----
julia packageInstall.jl
----

==== Commands


* Train
Code is built from a single csv file or from the .csv files put into
a directory, as resp. the second and third lines below.
[source,bash]
----
julia train.jl –-help
julia train.jl --path-lucidchart-csv resources/ISO-Strict.csv --brain-entry iso-strict --path-model resources/ISO-Strict.dat
----

* Transliterate single string (with debugging mode)
[source,bash]
----
julia runDBGCode.jl –-help
julia runDBGCode.jl --path-model resources/ISO-Strict.dat --text "رفتٌ رفتٌ"
# or
julia runDBGCode.jl --path-model resources/ISO-Strict.dat --text ﺮﻔﺗٌ
----

* Run Tests (data data/tests.csv)

run diacritization on file:
[source,bash]
----
julia run.jl –-help
# output to file
julia run.jl --path-model resources/ISO-Strict.dat --file-name data/test_poems.txt --file-name-out out.txt
----

run tests, with scores and error summary:
[source,bash]
----
----
