== Farsi Learn

==== Intro

Farsi learn is a software allowing a non technical experts to sketch
rules and logic steps needed for the task of transliteration of Farsi.

We have created this system to speed up and make flexible this general
part of the work.

While the language specialist can design and try easily his own rules,
the developer implements the code corresponding to the rules. This way
both tasks and roles are well defined and confined.

== Components & Steps

==== Learning Strategy

Original transliteration strategy https://github.com/interscript/transliteration-learner-from-graphs/blob/main/learn-graph/rules/rules.md[rules],
in a typical format...

In this project, we used lucidchart to generate a
https://github.com/interscript/transliteration-learner-from-graphs/blob/main/learn-graph/resources/Model1.0.png[diagram representation] of the above rules.

Such lucidchart diagram can be learnt and encoded into code from its
https://github.com/interscript/transliteration-learner-from-graphs/blob/main/learn-graph/resources/Model1.0.csv[csv export].

==== Diagram format

We structure logic flows as a set of graphs.
This scales by allowing a graph to call other graph logics.

Any diagram respecting the same formatting can be straightforwardly transformed
into code:

  * Entry Point of logic flows (or subfows):
   Start of any logic of sub logic Curly Brace Note
  * Nodes: Decision, Process and Terminator.

Obviously, the nodes and entries have to be connected by arrows in a consistent
manner.


==== Hazm library

Core of the strategy is the Hazm library, allowing to perform various operations
on farsi texts like tokenization, lemmatization, PoS tagging, ...

==== Mappings

Basis for the transliteration strategy are various mappings:
https://github.com/secryst/transliteration-learner-from-graph-models/releases/download/v0/raw_mappings.zip[link to mappings]

Following files are expected to be placed into /resources:

  *  Affixes.xlsx
  *  Entries.xlsx
  *  PoS_mappings.csv
  *  postagger.model


==== Models

Our models can be downloaded
https://github.com/secryst/transliteration-learner-from-graph-models/releases/download/v0/models.zip[here].

Files to be placed for instance into /resources are:

  *  Model.csv
  *  Model.dat
  *  Model.png

Model.dat is the precompiled model.

==== Run
After python & julia dependencies and have been taken care of,
as described in the steps below, one can start to transliterate in debug mode:
[source,bash]
----
julia transliterateSingleString.jl --path-model resources/Model0.1.dat  --farsi-text مزایایی --pos-tagging noun
----


==== Python Dependencies

Has to be ran alongside the python dependencies for legacy reasons
[source,bash]
----
pip install -r requirements.txt
----


==== Install Julia

https://julialang.org/downloads/[julia downloads]

==== Connect to Correct Python Path/Dependencies
[source,bash]
----
ENV[``PYTHON''] = ``…my python path with hazm installed…''
import Pkg; Pkg.add(``PyCall''); Pkg.build(``PyCall'')
----

==== Julia Dependencies

[source,bash]
----
julia packageInstall.jl
----

==== Commands

* Build ressources:
In python for legacy reasons.
Code is expecting following ressources /resources:

      Affixes.xlsx; Entries.xlsx; farsi_assets.pickle; postagger.model; PoS_mappings.csv

and builds:
      farsi_assets.pickle
[source,bash]
----
python script_to_build_assets.py
----

* Train
Code is built from a single csv file or from the .csv files put into
a directory, as resp. the second and third lines below.
[source,bash]
----
julia train.jl –-help
julia train.jl --path-lucidchart-csv resources/TestFarsiTrans.csv --brain-entry transliterator --path-model resources/TestFarsiTrans.dat
julia train.jl --dir-path-lucidchart-csv resources/modelDir/ --brain-entry transliterator --path-model resources/Model5.dat
----

* Transliterate single string (with debugging mode)
[source,bash]
----
julia transliterateSingleString.jl –-help
julia transliterateSingleString.jl --path-model resources/TestFarsiTrans.dat --farsi-text یویو --pos-tagging noun
----

* Run Tests (data data/tests.csv)

run diacritization on file:
[source,bash]
----
julia run.jl –-help
julia run.jl --path-model resources/TestFarsiTrans.dat --file-name data/test_poems.txt
----

run tests, with scores and error summary:
[source,bash]
----
julia run.jl --path-model resources/TestFarsiTrans.dat --file-name test
----
